f=open("two.txt","r")
data=f.read()
print("file content:",data)
f.close()

f=open("two.txt","r")
data=f.read(10)
print("first part:",data)
f.close()

f=open("two.txt")
lines=f.readlines()
print("list of lines:",lines)
print("number of lines:",len(lines))
f.close()

f=open("one.txt","r")
lines=f.readlines()
print(lines[1].strip())
f.close()